/*
    Object Type Icons - Written By Benjamin Jack Cullen.

    One 32x32 alpha-only icon bitmap per row of objectType[] (see
    SiderealObjectsTables.cpp / SiderealObjectTypeEntry), auto-generated by
    a small procedural script (not hand-authored pixel art) so each NGC/IC
    catalog object type has a distinct marker shape on the celestial sphere
    (see UnidentifiedStudios_CelestialSphere.cpp) instead of a plain dot.
    Each icon started as a 16x16 bitmap, still kept in the .cpp file, then
    2x bicubic-upscaled to the 32x32 bitmap actually returned here.
*/

#ifndef OBJECT_TYPE_ICONS_H
#define OBJECT_TYPE_ICONS_H

#include "lvgl.h"

// Returns the icon whose shape encodes SiderealObjectTypeEntry.num ==
// type_num (see objectType[] in SiderealObjectsTables.cpp), or nullptr if
// type_num is negative or matches no row of that table.
// Every icon is LV_COLOR_FORMAT_A8 (alpha-only, no color of its own): it is
// meant to be applied with lv_image_set_src() and tinted via
// lv_obj_set_style_image_recolor()/lv_obj_set_style_image_recolor_opa(),
// the same way a symbol/font glyph would be.
const lv_image_dsc_t * get_object_type_icon(int type_num);

// Plain filled-dot marker (also LV_COLOR_FORMAT_A8) for swept objects that
// don't classify through objectType[] at all (Messier, Caldwell and Other
// tables use their own/no type field) -- see getObjectTypeEntry() in
// UnidentifiedStudios_SiderealHelper.h.
extern const lv_image_dsc_t object_type_icon_fallback;

#endif
